Fixed ReceiveExternalFilesActivityIT not separating the screenshots
When running the screenshot tests, the following error was raised:

com.owncloud.android.ui.activity.ReceiveExternalFilesActivityIT > openMultiAccount[uiComparison(AVD) - 9] FAILED
java.lang.AssertionError: Can't create multiple screenshots with the same name: com.owncloud.android.ui.activity.ReceiveExternalFilesActivityIT_open
at com.facebook.testing.screenshot.internal.AlbumImpl.addRecord

This happened because openMultiAccount() simply calls the open() test which
"hardcodes" the screenshot name

Signed-off-by: Philipp Hasper <vcs@hasper.info>